### ISSUE TITLE
Posibles mejoras

### ISSUE THREAD

**Issue by ghost** [freaksparty/Ficonet#2]
No son fallos como tales, pero hasta ahora he detectado algunas posibles mejoras:
1.- Establecer un límite de plazas, para evitar asignar una plaza que no existe por error (si asigno la plaza 141 y sólo hay 140 no debería dejarme).
2.- Indicar el tipo de plaza. (normal o de organización...)
3.- Cuándo un admin modifica los datos de un usuario (password por ejemplo) Estaría bien informar al usuario.
4.- Cuándo un admin modifica la plaza de un usuario por una plaza ya existente (al usuario 1 le asigno la plaza 2 que ya estaba asignada). Muestra todo en verde indicando que no hay ningún problema. Al cambiarla, efectivamente no la cambia, pero muestra un error desconocido.

**Comment by Moussenger** [comment]
Cerrada para separar funcionalidades en diversas issues
