### ISSUE TITLE
Límite de plazas.

### ISSUE THREAD

**Issue by ghost** [freaksparty/Ficonet#3]
Establecer un límite de plazas, para evitar asignar una plaza que no existe por error (si asigno la plaza 141 y sólo hay 140 no debería dejarme).

**Comment by Moussenger** [comment]
En la intranet en realidad las plazas no son algo "útil". Las añadí por el tema de "juegos", es decir, el año pasado había lo de pokémon, que te asignaban uno por número de plaza. Este año haremos algo similar con algo del FFVII... 

El tema es que en la "intranet" no hay plazas erroneas (los orgas tambien tenemos "plaza". No veo ahi donde habria un limite). Es más un apoyo a ese tipo de juegos.

¿Qué opinais los demas?

**Comment by xiromoreira** [comment]
Lo veo un poco innecesario, lo ideal sería volcar las plazas de la web de inscripciones (no vamos a fichar las ~200 plazas a mano).

Tal vez se debería obviar el nº de plaza por ahora mientras no tenga uso.

Relacionado con el tema de auth unificada, el login de backend devuelve entre otros datos la plaza dentro del evento (o se puede preparar muy facilmente para hacerlo).
