### ISSUE TITLE
Notificaciones al usuario.

### ISSUE THREAD

**Issue by ghost** [freaksparty/Ficonet#5]
Notificar al usuario por mail cuándo se modifican sus datos (contraseña, nombre, mail), y pedir confirmación (por ejemplo , si se modifica el mail, enviar un correo de confirmación a la nueva dirección para que confirme el cambio).

**Comment by Moussenger** [comment]
El tema es que en la intranet no tiene por qué haber internet. Si lo hay, el usuario ya es notificado cuando le da a recuperar contraseña. 

Si no lo hay, entonces es cuando puede venir junto a un admin y pedir que se la cambien. En ese caso, la notificación carece de sentido porque la solicitud fue hecha al no haber internet.

¿Veis el resto útil esta funcionalidad?

**Comment by xiromoreira** [comment]
Tal como dices, es útil pero no crítica, una web interna se queda en el ámbito de la party y para eso ya están los BOFHs. Pero todo lo que sea automatizar y liberar trabajo a orga es positivo.

Si se hace hay que tener en cuenta la posibilidad de que no haya red (un encolado bueno que no pierda emails).

**Comment by ghost** [comment]
"El tema es que en la intranet no tiene por qué haber internet". No había pensado yo en eso. Yo lo planteaba para evitar errores del tipo: se modificó la pass del usuario por error, o peor aún, se modifica el mail, el usuario no se entera (y no puede recuperar la contraseña porque no tiene ese mail), tiene que acudir a orga para que lo arreglen... En caso de que la intranet no tenga internet, pues deja un poco inútil la funcionalidad, la verdad.
