### ISSUE TITLE
Plazas de usuarios dados de baja.

### ISSUE THREAD

**Issue by ghost** [freaksparty/Ficonet#9]
Si yo doy de baja un usuario (pongamos que tiene la plaza 200) entiendo que ese usuario está inactivo y por tanto no tiene plaza en la party, sin embargo, al asignar a otro usuario su plaza (es decir modifico un usuario 2 para que ocupe ahora la plaza 200) No permite hacerlo.
¿Qué opináis? ¿Deberíamos guardar el número de plaza de un usuario dado de baja? De ser así habría que modificar el caso de uso "recuperar usuario", ya que habría que asignarle de nuevo una plaza.

**Comment by Moussenger** [comment]
Cuando das de baja un usuario, este sigue existiendo, es decir, su plaza se mantiene, solo que no está "habilitado" para utilizar la intranet en ese momento, pero se puede recuperar con todos sus datos.

Es distinto al borrado definitivo, que solo lo puede hacer un "GOD" cuando está el usuario dado de baja e implica el borrado de todos sus datos y todos los datos relacionados (peligroso, porque puede crear inconsistencias, por eso solo un "GOD" puede hacerlo).

Cuando el borrado es definitivo, sí que se puede volver a utilizar esa plaza porque ya no existe en la base de datos.

De nuevo, lo de las plazas es un artificio para "juegos" (como lo de los pokemon el año pasado). No tienen más relevancia que eso en el funcionamiento de la intranet, es decir, no es crítico ponerle un número u otro.

Aunque si que están bien las comprobaciones como la issue #8 , ya que las plazas negativas si que sería un error
